### PR TITLE
Report reordering

### PR DESCRIPTION
**Pull request by diegocasmo**
Related to #18

### CODE REVIEW

**Comment by ankurshukla03** [comment]
report reordering has been done
right?
so should we merge this branch?

**Comment by diegocasmo** [comment]
@ankurshukla03 review first, ask questions/comments if any

**Comment by ankurshukla03** [comment]
Name of 3rd section is Deep learning and then at subsection 3.2 we are defining deep learning. Doesn't it look odd we are naming the section as Deep learning but we are defining Deep learning in one of the subsections?

**Comment by ankurshukla03** [comment]
We can name that section as a methodology(because we are using this method for solving the problem)

**Comment by diegocasmo** [comment]
@ankurshukla03 I have renamed the section to "Theory" instead. IMO, "Methodology" sounds more like the implementation section

**Comment by ankurshukla03** [comment]
Yeah now it looks much better

**Comment by diegocasmo** [comment]
@ankurshukla03 @tristaaan I need any of you to approve the changes, otherwise it can't be merged

**Review by ankurshukla03 — APPROVED** [review]

**Pull request merged**
