### PR TITLE
Abstract

### PR DESCRIPTION
**Pull request by ankurshukla03**
Closes #43 
First Draft of abstract. Tried to answered first two question in #41.

### CODE REVIEW

**Comment by ankurshukla03** [comment]
PTAL

**Comment by diegocasmo** [comment]
A little bit of inspiration from a paper similar to ours (ideally ours should read somewhat similar to it):

```Most existing star-galaxy classifiers use the reduced summary information from catalogs, re- quiring careful feature extraction and selection. The latest advances in machine learning that use deep convolutional neural networks allow a machine to automatically learn the features di- rectly from data, minimizing the need for input from human experts. We present a star-galaxy classification framework that uses deep convolutional neural networks (ConvNets) directly on the reduced, calibrated pixel values. Using data from the Sloan Digital Sky Survey (SDSS) and the Canada-France-Hawaii Telescope Lensing Survey (CFHTLenS), we demonstrate that ConvNets are able to produce accurate and well-calibrated probabilistic classifications that are competitive with conventional machine learning techniques. Future advances in deep learning may bring more success with current and forthcoming photometric surveys, such as the Dark Energy Survey (DES) and the Large Synoptic Survey Telescope (LSST), because deep neural networks require very little, manual feature engineering.```

**Comment by tristaaan** [comment]
I'm having a hard time with this sentence, I like it but can't figure out how to tersely reword it:

"Training the model with a given \numprint{61578} images by tuning batch and image sizes attained a Top 100 score in the Kaggle scoreboard."

**Comment by ankurshukla03** [comment]
> "Training the model with a given \numprint{61578} images by tuning batch and image sizes attained a Top 100 score in the Kaggle scoreboard."

Maybe the starting of the sentence is off.

**Comment by tristaaan** [comment]
"The model was trained on a dataset of \numprint{61578} images with a variety of batch sizes and input formats. Many of these methods ultimately attained a Top 100 score on the Kaggle leaderboards."

? Feel free to alter.

**Comment by ankurshukla03** [comment]
> Many of these methods ultimately attained a Top 100 score on the Kaggle leaderboards."

One of the methods ultimately attained a Top 100 score on the Kaggle leaderboards.??

**Comment by ankurshukla03** [comment]
Conclusion of the abstract still looks bit off.

**Comment by tristaaan** [comment]
That's good yes

**Comment by tristaaan** [comment]
These don't make any sense: 

- "The idea presented here is to combine star galaxy with CNN."
- "calibrated pixel values"?
- "...thus giving required results from reduced sets of user input"?

**Comment by diegocasmo** [comment]
IMO, ``This would be applied directly on the dimensionally reduced, calibrated pixel values, thus giving required results from reduced sets of user input`` sounds way too complicated. There must be a simpler way to explain what we did.

**Review by diegocasmo — COMMENTED** [review]
- Remove ``of``?
  - ``[..] test images and \numprint{61578} training images 'of' which were [..]``
- Add ``a``?
  - ``placed highly in [a] prestigious image``

**Review by diegocasmo — APPROVED** [review]
LGTM

**Pull request merged**
